name: CI/CD with SSH Password & YUM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to Server
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'

          if [ ! -d "/home/user/your-repo" ]; then
            git clone https://dev-ashutoshsharma:${{ secrets.TOKEN_GITHUB }}@github.com/dev-ashutoshsharma/payload-banner-app.git /root/banner-app
          fi

          cd /root/banner-app

          git pull origin main
          npm install
          pm2 delete payload-app || true
          pm2 start npm --name "payload-app" -- Serve
          pm2 save
          pm2 startup

          EOF
